language: ruby
cache: bundler
bundler_args: --without development

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0

gemfile:
  - Gemfile
  - Gemfile.1.8.7

matrix:
  fast_finish: true

  allow_failures:
    - rvm: 2.1.0

  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: Gemfile.1.8.7
    - rvm: 2.0.0
      gemfile: Gemfile.1.8.7
    - rvm: 2.1.0
      gemfile: Gemfile.1.8.7
